## 1. Imports

In [108]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

## 2. Create a `soup` object

In [109]:
with open("sample_html.html") as file:
	soup = BeautifulSoup(file, "html.parser")

In [110]:
type(soup)

bs4.BeautifulSoup

## 3. Basics of the `soup` object

- `prettify()`
- individual tags:
    - `title`
    - `a`
    - `p`
- `text`
- `name`
- `parent`
- `children`
- `descendants`
- `get_text()`
- `find()`
- `find_all()`
- `get()` / square bracket notation

In [111]:
# prettify

print(soup.prettify())

<html>
 <head>
  <title>
   The Dormouse's story
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The Dormouse's story
   </b>
  </p>
  <p class="story">
   Once upon a time there were three little sisters; and their names were
   <a class="sister" href="http://example.com/elsie" id="link1">
    Elsie
   </a>
   ,
   <a class="sister" href="http://example.com/lacie" id="link2">
    Lacie
   </a>
   and
   <a class="sister" href="http://example.com/tillie" id="link3">
    Tillie
   </a>
   ;
and they lived at the bottom of a well.
  </p>
  <p class="story">
   ...
  </p>
 </body>
</html>

In [112]:
soup.title

In [113]:
soup.a

In [114]:
soup.p

In [115]:
# text

soup.title

In [116]:
type(soup.title)

bs4.element.Tag

In [117]:
soup.title.text

"The Dormouse's story"

In [118]:
type(soup.title.text)

str

In [119]:
soup.title.text.upper()

"THE DORMOUSE'S STORY"

In [120]:
soup.title.text.lower()

"the dormouse's story"

In [121]:
soup.title.text.split()

['The', "Dormouse's", 'story']

In [122]:
# name

soup.title

In [123]:
soup.title.name

'title'

In [124]:
# parent

soup.title.parent

In [125]:
soup.title.parent.parent

<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p></body></html>

In [126]:
# children

soup.body

<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p></body>

In [127]:
soup.body.children

In [128]:
for child in soup.body.children:
	print(child)

<p class="title"><b>The Dormouse's story</b></p>


<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>


<p class="story">...</p>

In [129]:
for child in soup.head.children:
	print(child)

<title>The Dormouse's story</title>

In [130]:
# descendants

soup.body.descendants

In [131]:
for descendant in soup.body.descendants:
	print(descendant)

<p class="title"><b>The Dormouse's story</b></p>
<b>The Dormouse's story</b>
The Dormouse's story


<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
Once upon a time there were three little sisters; and their names were

<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>
Elsie
,

<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>
Lacie
 and

<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>
Tillie
;
and they lived at the bottom of a well.


<p class="story">...</p>
...

In [132]:
# get_text()

soup.body

<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p></body>

In [133]:
soup.body.get_text()

"\nThe Dormouse's story\nOnce upon a time there were three little sisters; and their names were\nElsie,\nLacie and\nTillie;\nand they lived at the bottom of a well.\n..."

In [134]:
print(soup.body.get_text().strip())

The Dormouse's story
Once upon a time there were three little sisters; and their names were
Elsie,
Lacie and
Tillie;
and they lived at the bottom of a well.
...

In [135]:
type(soup.body.get_text())

str

In [136]:
soup.title.get_text()

"The Dormouse's story"

In [137]:
# find()

soup.a

In [138]:
soup.find('a')

In [139]:
# find_all()

soup.find_all('a')

[<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>]

In [140]:
type(soup.find_all('a'))

bs4.element.ResultSet

In [141]:
# get()

soup.a

In [142]:
soup.a['id']

'link1'

In [143]:
soup.a.get('class')

['sister']

In [144]:
soup.a.get('href')

'http://example.com/elsie'

In [145]:
soup.a.get('id')

'link1'

## 4. Fetching webpage with `Requests`

- URL: `https://www.bbc.com/sport/football/premier-league/top-scorers`

In [146]:
# GET request

url = "https://www.bbc.com/sport/football/premier-league/top-scorers"

response = requests.get(url)

In [147]:
# check for errors

response.raise_for_status()

In [148]:
print(response.raise_for_status())

None

In [149]:
# status code

response.status_code

200

In [150]:
# text (string format)

response.text[:200]

'<!DOCTYPE html><html lang="en-GB" class="no-js"><head><meta charSet="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title data-rh="true">Premier League Top Scorers - B'

In [151]:
type(response.text)

str

In [152]:
# content (binary format)

response.content[:200]

b'<!DOCTYPE html><html lang="en-GB" class="no-js"><head><meta charSet="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title data-rh="true">Premier League Top Scorers - B'

In [153]:
type(response.content)

bytes

- can use either `content` or `text` attribute to create the soup object
- with `text`, we must be certain about the encoding
- with `content`, we let Beautiful Soup handle the encoding mostly

In [154]:
# soup object

soup = BeautifulSoup(response.content, "html.parser")

In [155]:
print(soup.prettify())

<!DOCTYPE html>
<html class="no-js" lang="en-GB">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title data-rh="true">
   Premier League Top Scorers - BBC Sport
  </title>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" name="description"/>
  <meta content="#FFFFFF" data-rh="true" name="theme-color"/>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" property="og:description"/>
  <meta content="https://static.files.bbci.co.uk/core/website/assets/static/sport/bbc-sport-logo.0da9386782.png" data-rh="true" property="og:image"/>
  <meta content="BBC Sport" data-rh="true" property="og:site_name"/>
  <meta content="Premier League Top Scorers - BBC Sport" data-rh="true" property="og:title"/>
  <meta content="article" data-rh="true" property="og:type"/>
  <meta content="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" data-rh="true" property="og:url"/>
  <meta content="summary" data-rh="true" name="twitter:card"/>
  <meta content="@BBCSport" data-rh="true" name="twitter:creator"/>
  <meta content="@BBCSport" data-rh="true" name="twitter:site"/>
  <meta content="Premier League Top Scorers - BBC Sport" data-rh="true" name="twitter:title"/>
  <meta content="Premier League top scorers. Showing assists, time on pitch and the shots on and off target." data-rh="true" name="twitter:description"/>
  <meta content="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" data-rh="true" name="twitter:url"/>
  <meta content="https://static.files.bbci.co.uk/core/website/assets/static/icons/windows-phone/sport/windows-phone-icon-270x270.3e5b0f9ac9.png" data-rh="true" name="msapplication-TileImage" type="metaTags"/>
  <meta content="telephone=no" data-rh="true" name="format-detection"/>
  <meta content="max-image-preview:large" data-rh="true" name="robots"/>
  <link data-rh="true" href="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" rel="canonical"/>
  <link data-rh="true" href="https://www.bbc.co.uk/sport/football/premier-league/top-scorers" hreflang="en-gb" rel="alternate"/>
  <link data-rh="true" href="https://www.bbc.com/sport/football/premier-league/top-scorers" hreflang="en" rel="alternate"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-36.4462ac53e0.png" rel="icon" sizes="36x36" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-48.889764e1f5.png" rel="icon" sizes="48x48" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-57.d66bb4d3af.png" rel="icon" sizes="57x57" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-60.ea49e5ffb8.png" rel="icon" sizes="60x60" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-72.1e5fc819b5.png" rel="icon" sizes="72x72" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-76.34703514a6.png" rel="icon" sizes="76x76" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-96.a040328c4e.png" rel="icon" sizes="96x96" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-114.fe9c3f2019.png" rel="icon" sizes="114x114" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-120.8ed642b324.png" rel="icon" sizes="120x120" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-128.120915c059.png" rel="icon" sizes="128x128" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-144.15dd10e42c.png" rel="icon" sizes="144x144" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-152.fd46d402eb.png" rel="icon" sizes="152x152" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-180.f21cfb03df.png" rel="icon" sizes="180x180" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-192.79e4069625.png" rel="icon" sizes="192x192" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-384.ae211a8aa4.png" rel="icon" sizes="384x384" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/touch/sport/touch-icon-512.239d26b83e.png" rel="icon" sizes="512x512" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/sport/favicon-16.ffa949edba.png" rel="icon" sizes="16x16" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/website/assets/static/icons/favicon/sport/favicon-32.729e81a820.png" rel="icon" sizes="32x32" type="image/png"/>
  <link data-rh="true" href="https://static.files.bbci.co.uk/core/manifest.1ccdbcfd4cc3bf889128a50903c2b22c81758637.json" rel="manifest"/>
  <script nonce="8NF4arm5IoRqvJEVmcoZCnBeyp0yIkmzArPFU61N1sSTaqQiT1">
   document.querySelector("html").classList.remove("no-js")
  </script>
  <style data-emotion="ssrcss-global zg3a55">
   html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,main,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section{display:block;}:root{interpolate-size:allow-keywords;}body{line-height:1;-webkit-text-size-adjust:none;-moz-text-size-adjust:none;-ms-text-size-adjust:none;text-size-adjust:none;}ol,ul{list-style:none;}blockquote,q{quotes:none;}blockquote::before,blockquote::after,q::before,q::after{content:'';content:none;}table{border-collapse:collapse;border-spacing:0;}button{-webkit-appearance:none;-moz-appearance:none;-ms-appearance:none;appearance:none;margin:0;padding:0;background:none;border-radius:0;border:0;font-family:inherit;color:inherit;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Rg.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Rg.woff) format('woff');font-display:swap;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_It.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_It.woff) format('woff');font-display:swap;font-style:italic;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_BdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_BdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:700;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Lt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Lt.woff) format('woff');font-display:swap;font-weight:300;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_LtIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_LtIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:300;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_ExBdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:800;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Md.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_Md.woff) format('woff');font-display:swap;font-weight:500;}@font-face{font-family:'ReithSans';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_MdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSans_W_MdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:500;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Rg.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Rg.woff) format('woff');font-display:swap;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_It.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_It.woff) format('woff');font-display:swap;font-style:italic;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_BdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_BdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:700;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Lt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Lt.woff) format('woff');font-display:swap;font-weight:300;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_LtIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_LtIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:300;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_ExBdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:800;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Md.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_Md.woff) format('woff');font-display:swap;font-weight:500;}@font-face{font-family:'ReithSerif';src:url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_MdIt.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith/2.512/BBCReithSerif_W_MdIt.woff) format('woff');font-display:swap;font-style:italic;font-weight:500;}@font-face{font-family:'ReithRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithRd_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}@font-face{font-family:'ReithSemiRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_Bd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_Bd.woff) format('woff');font-display:swap;font-weight:700;}@font-face{font-family:'ReithSemiRounded';src:url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_ExBd.woff2) format('woff2'),url(https://static.files.bbci.co.uk/fonts/reith-rounded/2.000/BBCReithSmRd_W_ExBd.woff) format('woff');font-display:swap;font-weight:800;}body{background-color:#FFFFFF;}:focus-visible{box-shadow:0 0 0 0.125rem #FFFFFF;outline:0.125rem solid #000000;outline-offset:0.125rem;}
  </style>
  <style data-emotion="ssrcss 181c4hk-SectionWrapper 1imfos9-PageStack z8pk48-GlobalNavigation 4y0s1t-Wrap 1bvvlvf-GlobalNavigationContent 1c5rwo1-GlobalNavigationItem col7sy-NavigationLink-LogoLink 13kjque-LogoIconWrapper 1f39n02-VisuallyHidden 1hjcemq-AccessibilityLinkList 1ubr254-AccessibilityLink bje5xb-GlobalNavigationItem 1o1nzph-AccountOptionsList 1t7ltsf-GlobalNavigationProduct-GlobalNavigationAccount 5fw2ee-AccountComponentWrapper uwr32o-StyledAccountPlaceholderComponent n7m3zs-StyledLoadingPlaceholderWrapper h8wpjv-StyledAccountPlaceholderIconWrapper 1ce2si-Skeleton-StyledAccountPlaceholderIcon h42kmd-StyledLoadingPlaceHolderTextWrapper 11sxr8p-Skeleton-StyledLoadingPlaceHolderText 11dv7o-NavigationLink-AccountLink 1oeiyy4-ForYouIconWrapper xi5oyi-StyledIcon bvzllz-AccountText 12xrmhv-VerticalSeparator d2bys-GlobalNavigationBarLinkList 1bwqj1o-GlobalNavigationProduct 15owa93-NavigationLink 132qwvs-NavItemHoverState 1oqvpc8-NavigationLink-MenuToggleControlLink 14kc44w-NavItemHoverState 13dpa8i-DotsMenuIconWrapper 1naw1ix-LastGlobalNavigationItem 1sakhrp-GlobalNavigationItem-GlobalNavigationBurger 1myt22i-BurgerMenuIconWrapper cl7jld-GlobalNavigationItem rrztoo-NavigationLink-SearchLink 1lc3dkf-IconWrapper-SearchIconWrapper 1rstd29-SearchText 91jqb8-GlobalNavigationDrawer yhcsrq-GlobalNavigationMoreMenu 1obp207-MenuWrapper a9g9c0-MenuLinkList 1cnl2eg-MenuLinkListItem kffy1u-MenuLink h8eoet-CloseButtonWrapper 1maygca-CallToActionLink 1hfawy1-IconWrapper 11h1iqi-ProductNavigationContainer icu1rp-Masthead 12x0ma7-ContentWrapper 1nqrevo-LogoWrapper 1vyfvn-LogoLink 18958r2-LogoIcon gmdx8l-Navigation ehbb92-MainNavBarContainer 40dop0-MenuContainer-PrimaryNavBarContainer 15o6r8s-PrimaryListContainer 1xa2nq9-ToggleContainer ckisij-StyledToggle uq8y1d-IconWrapper 1or42oc-MenuListContainer 1vxmun4-StyledMenuList or45ca-StyledMenuItem 162z3cq-StyledLink 1u47p8g-LinkTextContainer t8swvy-StyledLink zfkh5e-ToggleContainer 36jm8h-MenuContainer-MoreMenuWrapper wdgq9j-MoreMenuListContainer j6f6xh-MenuListContainer 1mlqmic-ListTitle 1mt0jbo-StyledMenuList g1n074-StyledMenuItem 1bzy3wo-StyledLink i9csl0-LinkTextContainer 19dj471-MenuContainer-SecondaryNavBarContainer 1toi6ts-MenuListContainer 18a3ezq-StyledMenuList 1y9ep4i-StyledMenuItem 13wbrke-StyledLink 1mstwv3-LinkTextContainer p4fm83-IconContainer 1ncu3vb-StyledLink t9s73x-StandardZone gqrsw0-Wrapper 1qdh4qq-HeadingWrapper pbttu9-Heading 59a716-SearchWrapper 1hy9pi-StyledComboboxWrapper xifuke-StyledWrapper 2j3s5k-SearchBarWrapper 1gbn3xw-StyledDiv kxppca-FocusDiv zbw5ic-IconWrapper 9pm56o-StyledInput 1ps7ft7-StyledFormWrapper 1y4i773-Button 1ujodfj-FallbackMessage 1cifq5e-GlobalFooterStyling 2vow6d-Stack rkzzm9-Columns 29l7i3-Link-NavigationLink 1ml6m0y-Stack 17ehax8-Cluster 17o89of-ClusterItems 1d9p81h-Link-LegalLink 1q0x1qg-Paragraph bosb8n-Link">

## 5. HTML parsing with `Beautiful Soup`: A Mini Project

- scrape data from a public website
- organize the data as a dataframe
- export the data as an excel sheet

In [156]:
url = 'https://www.bbc.com/sport/cricket/mens-england-division-one-multi-day/table'

In [157]:
team_names = []
played = []
won = []
lost = []
drawn = []
points = []

In [158]:
try:
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content, 'html.parser')
    teams = soup.find('table').find_all('tr', class_='ssrcss-qqhdqi-TableRowBody e1icz100')

    for team in teams:
        team_name = team.find('div', class_='ssrcss-1m4x485-DesktopWidthOnly e1sk6csp2').get_text(strip=True)

        stats = team.find_all('div', class_='ssrcss-1vo7v3r-CellWrapper ef9ipf0')
        matches_played = int(stats[0].get_text(strip=True))
        matches_won = int(stats[2].get_text(strip=True))
        matches_lost = int(stats[4].get_text(strip=True))
        matches_drawn = int(stats[6].get_text(strip=True))
        total_points = int(team.find('div', class_='ssrcss-18ap757-CellWrapper ef9ipf0').get_text(strip=True))
        
        team_names.append(team_name)
        played.append(matches_played)
        won.append(matches_won)
        lost.append(matches_lost)
        drawn.append(matches_drawn)
        points.append(total_points)

    data = {
        'Team': team_names,
        'Played': played,
        'Won': won,
        'Lost': lost,
        'Drawn': drawn,
        'Points': points
    }
    df_teams = pd.DataFrame(data)

In [159]:
df_teams

              Team  Played  Won  Lost  Drawn  Points
0           Surrey      10    3     0      7     154
1  Nottinghamshire      10    4     1      5     153
2         Somerset      10    4     2      4     137
3     Warwickshire      10    3     1      6     136
4           Sussex      10    3     3      4     125
5        Hampshire      10    2     2      6     117
6            Essex      10    2     3      5     112
7           Durham      10    2     4      4     111
8        Yorkshire      10    2     4      4     104
9   Worcestershire      10    1     6      3      78

In [160]:
df_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Team    10 non-null     object
 1   Played  10 non-null     int64
 2   Won     10 non-null     int64
 3   Lost    10 non-null     int64
 4   Drawn   10 non-null     int64
 5   Points  10 non-null     int64
dtypes: int64(5), object(1)
memory usage: 612.0+ bytes

In [161]:
df_teams.describe()

       Played        Won       Lost      Drawn      Points
count    10.0  10.000000  10.000000  10.000000   10.000000
mean     10.0   2.600000   2.600000   4.800000  122.700000
std       0.0   0.966092   1.776388   1.229273   23.371635
min      10.0   1.000000   0.000000   3.000000   78.000000
25%      10.0   2.000000   1.250000   4.000000  111.250000
50%      10.0   2.500000   2.500000   4.500000  121.000000
75%      10.0   3.000000   3.750000   5.750000  136.750000
max      10.0   4.000000   6.000000   7.000000  154.000000

In [162]:
df_teams.to_excel('Cricket_County_Championship.xlsx', index=False)